## TODO: define standard database - Greengenes, incl. in package data?

#' Taxonomy assignment based on external reference database in BiMiCo pipeline
#'
#' Generates taxonomic assignment of ASV sequences, given an ASV table generated by BiMiCo and an external taxonomic reference database compatible with DADA2 'assignTaxonomy' function. Currently Greengenes v13.5 is provided with the package.
#' @param asvtab (Required) ASV table object (of class matrix) created by the 'std_(454/Illum)_ASVtab' function (ASVs in rows, samples in columns)
#' @param taxdat (Required) Path to taxonomy database file compatible with DADA2 'assignTaxonomy' function
#' @param mtthread (Required) Boolean, enables multithreading (not recommended in Rstudio)
#' @keywords read processing dada2
#' @export
#' @examples
#' asgntax()


asgntax <- function(asvtab, taxdat, revcomp, mtthread){

  asstax <- dada2::assignTaxonomy(t(asvtab),
                             taxdat,
                             multithread=mtthread,
                             tryRC = revcomp)

 return(asstax)

  }
