#'bimico_summary
#'
#'Generate a basic summary report based on the desired variable column of phenodata (case/control, sample source, sequencing batch...)
#' @param phylo (Required) Phyloseq object generated by bimico_454/bimico_illum
#' @param contrast (Required) column name of phenodata with the variable of interest
#' @param outfile (Required) output filename
#' @keywords 16S data analysis
#' @export
#' @examples
#' bimico_summary()


bimico_summary <- function(phylo, contrast, outfile){
  
  p1 <- phyloseq::transform_sample_counts(phylo, function(x) x/sum(x)*1000)
  
  p2 <- as.data.frame(rowSums(as.matrix(p1@otu_table)))
  colnames(p2) <- "relab" 
  p2 <- p2[ order(1/p2$relab), ,drop=F ]
  
  p3 <- as.data.frame(p1@otu_table)
  p4 <- as.matrix(p1@sam_data)
  
  pdfpath=paste0(outfile, ".pdf")
  
  pdf(file = pdfpath)
  
    print(pcoa_ph(p1, contrast))
    par(mfrow=c(2,2))
    plot(as.numeric(p3[ rownames(p2)[1], ])~as.factor(p4[ , contrast]),
         col="lightblue",
         main=rownames((p3[ rownames(p2)[1], ])))
    plot(as.numeric(p3[ rownames(p2)[2], ])~as.factor(p4[ , contrast]),
         col="lightblue",
         main=rownames((p3[ rownames(p2)[2], ])))
    plot(as.numeric(p3[ rownames(p2)[3], ])~as.factor(p4[ , contrast]),
         col="lightblue",
         main=rownames((p3[ rownames(p2)[3], ])))
    plot(as.numeric(p3[ rownames(p2)[3], ])~as.factor(p4[ , contrast]),
         col="lightblue",
         main=rownames((p3[ rownames(p2)[3], ])))
    mtext("Top 4 most abundant ASVs", outer = T, line = -1, cex = 1)

  dev.off()
  }
  
  
  
  
  
  
