#'tidy_ASV_tables
#'
#' Rename ASVs with more convenient short names 
#' @param asvtab (Required) ASV table generated by bimico pipeline
#' @keywords 16S data analysis
#' @export
#' @examples
#' tidy_ASV_tables()


tidy_ASV_tables <- function(asvtab) {
  
  # write fasta file
  asv_seq <- rownames(asvtab)
  asv_name <- vector(dim(asvtab)[1], mode = "character")
  for (i in 1:dim(asvtab)[1]) { 
    asv_name[i] <- paste("ASV", i, sep = "_")
  }
  asv_seqs <- as.data.frame(asv_seq)
  rownames(asv_seqs) <- asv_name

  return(asv_seqs)
  
}
