#'Write_ASV_tables
#'
#'Save outputs of BiMiCo preprocessing steps with consistent naming/file formats. Outputs ASV count matrix, fasta file of ASV sequences, taxonomy table and optionally phenodata.
#'
#' @param asvtab (Required) ASV table generated by DADA2
#' @param taxtab (Required) Taxonomy table generated by DADA2
#' @param outname (Required) Output base filename (without extension)
#' @param outdir (Optional) Output directory. Default="./"
#' @param samdat (Optional) Sample phenotype data
#' @keywords read processing dada2
#' @export
#' @examples
#' write_ASV_tables()


write_ASV_tables <- function(asvtab, taxtab, outname, outdir="./", samdat=0) {

  if (dir.exists(outdir)){
    " ok "
  } else {
  dir.create(file.path(outdir))
  }
  
  # write fasta file
  asv_seqs <- rownames(asvtab)
  asv_headers <- vector(dim(asvtab)[1], mode = "character")
  for (i in 1:dim(asvtab)[1]) { 
    asv_headers[i] <- paste(">ASV", i, sep = "_")
  }
  asv_fasta <- c(rbind(asv_headers, asv_seqs))
  
  write(asv_fasta, paste0(outdir, outname, ".fasta"))

  
  # write ASV table
  
  
}
